### ISSUE TITLE
Undefined name 'attn_dict' in transformer_decoder.py

### ISSUE THREAD

**Issue by cclauss** [facebookresearch/inversecooking#1]
flake8 testing of https://github.com/facebookresearch/inversecooking on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./src/modules/transformer_decoder.py:319:17: F821 undefined name 'attn_dict'
                attn_dict[key][p] = attn[key]
                ^
1     F821 undefined name 'attn_dict'
1
```

**Comment by amaiasalvador** [comment]
Fixed by 3ab629c08f0b5d84bbc3d56ac70ce12e60500322 .
