### ISSUE TITLE
RuntimeError: expected device cpu and dtype Byte but got device cpu and dtype Bool

### ISSUE THREAD

**Issue by gabrielziegler3** [facebookresearch/inversecooking#10]
Hello, I get the following exception when running the last cell in the demo.ipynb.
![image](https://user-images.githubusercontent.com/18370133/64626768-c1cd0380-d3c4-11e9-8414-2fcb86ee8177.png)
I am using an Intel i7-4700HQ 8 threads, Arch Linux. I haven't changed any bit of the code. Is there something I should've done?

Thanks

**Comment by abjelodar** [comment]
I have the same issue.

**Comment by myDennisCode** [comment]
What pytorch version did you used ? Did you try it with the recommended version?

**Comment by mydennisee** [comment]
Just run this `conda install pytorch=0.4.1 cuda90 -c pytorch`

**Comment by abjelodar** [comment]
Thanks. It worked.

**Comment by gabrielziegler3** [comment]
That is true. I had torchvision on 0.4.0 which got me confused. 
The `requirements.txt` should be updated to contain the correct versions.

```
torch==0.4.1
torchvision==0.2.1
```
