### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by crazygirl1992** [facebookresearch/inversecooking#13]
hello, how many are gpus used and how long is the training time?

thank you very much!

**Comment by amaiasalvador** [comment]
The ingredient decoder was trained on 2 GPUs in about 24h. The instruction decoder takes roughly 15h to train on 8 GPUs.

**Comment by josephbiko** [comment]
What are the dram requirements? I get really high memory usage, but ~40% gpu utilization on a t4 for the ingredient decoder.
