### ISSUE TITLE
During the test process, why input the ground truth recipe to generated recipes and evaluate it?

### ISSUE THREAD

**Issue by Longcuirong** [facebookresearch/inversecooking#14]
Dear author，I have a problem. During the test process, why input the ground truth recipe to generated recipes and evaluate it?
why not use the recipes in the sample process and calculate its perplexity？

**Comment by amaiasalvador** [comment]
Perplexity gives a measure of how likely is a language model to predict the ground truth sentence (the true recipe). In this work, we use perplexity only to compare instruction decoder architectures (Table 1-left in the paper), which are trained to predict recipes word-by-word given a) the true ingredients and b) a food image.  However, when generating new recipes directly from images, we replace real ingredients with predicted ones to decode the recipe instructions.
