### ISSUE TITLE
perminv_ingrs argument not found in the code

### ISSUE THREAD

**Issue by BornaGhotbi** [facebookresearch/inversecooking#4]
What is the use of perminv_ingrs argument? And in case it is useful, it is not included in args.py. train.py is only working without this argument.

**Comment by amaiasalvador** [comment]
That argument is deprecated and is not used anywhere in the released code. The README has been updated to remove this argument from the instructions 9f2a462997cc4872fb10e9aa74228ae84b07f309 .
