### ISSUE TITLE
Uploading the `args.pkl` used to build the `modelbest.ckpt`

### ISSUE THREAD

**Issue by AdityaSidharta** [facebookresearch/inversecooking#5]
Hi, I would like to use the model checkpoint and fine tune it on my data. However, I am unable to load the state dictionary, `merge_model`, because I don't know what `args.pkl` is used to construct the `modelbest.ckpt`. Is it possible for the `args.pkl` to be uploaded as well? Thank you so much!

**Comment by amaiasalvador** [comment]
The pretrained model can be loaded using the default arguments provided in ```args.py``` . This is shown in ```src/demo.ipynb```.

**Comment by AdityaSidharta** [comment]
Got it! Thanks for your help, great work :)
