### ISSUE TITLE
Return instruction metrics (F1 and IoU)

### ISSUE THREAD

**Issue by xinfu607** [facebookresearch/inversecooking#9]
Would you please release instruction metrics (F1 and IoU).

**Comment by amaiasalvador** [comment]
F1 and IoU are the metrics we use to evaluate ingredient prediction, which are implemented in ```src/utils/metrics.py```. These can be computed for any trained model by running ```src/sample.py```. This script can also be used to compute the perplexity, which is the only metric we use for instructions.
